routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SSO\SSOController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CetegoryController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PelangganController;
use App\Http\Controllers\PembelianController;
use App\Http\Controllers\PenjualanController;
use App\Http\Controllers\PenjualanDetailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [DashboardController::class, 'index']);

Route::resource('/pelanggan', PelangganController::class);
Route::get('/pelanggan', [PelangganController::class, 'index'])->name('pelanggan.index');
Route::get('/create-pelanggan', [PelangganController::class, 'create'])->name('pelanggan.create');
Route::get('edit{id}-pelanggan/', [PelangganController::class, 'edit'])->name('pelanggan.edit');
Route::get('show{id}-pelanggan/', [PelangganController::class, 'show'])->name('pelanggan.show');
Route::get('/exportpelanggan', [PelangganController::class, 'pelangganexport'])->name('exportpelanggan');

Route::resource('/produk', ProdukController::class);
Route::get('/produk', [ProdukController::class, 'index'])->name('produk.index');
Route::get('/create-produk', [ProdukController::class, 'create'])->name('produk.create');
Route::get('edit{id}-produk/', [ProdukController::class, 'edit'])->name('produk.edit');
Route::get('show{id}-pelanggan/', [ProdukController::class, 'show'])->name('produk.detail');
Route::get('/exportproduk', [ProdukController::class, 'produkexport'])->name('exportproduk');

Route::resource('/supplier', SupplierController::class);
Route::get('/supplier', [SupplierController::class, 'index'])->name('supplier.index');
Route::get('create-supplier', [SupplierController::class, 'create'])->name('supplier.create');
Route::get('edit{id}-supplier/', [SupplierController::class, 'edit'])->name('supplier.edit');
Route::get('show{id}-supplier/', [SupplierController::class, 'show'])->name('supplier.show');
Route::get('/exportsupplier', [SupplierController::class, 'supplierexport'])->name('exportsupplier');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
});

Route::resource('kategori', CetegoryController::class);
// Route::get('/exportkategori', [CetegoryController::class, 'kategoriexport'])->name('kategori');


Route::controller(GoogleController::class)->group(function(){
    Route::get('login/google', 'redirectToGoogle')->name('auth.google');
    Route::get('login/google/callback', 'handleGoogleCallback');
});

Route::resource('/pembelian', PembelianController::class);
Route::get('/pembelian', [PembelianController::class, 'index'])->name('pembelian.index');
Route::get('/create-pembelian', [PembelianController::class, 'create'])->name('pembelian.create');
Route::get('show{id}-pembelian/', [PembelianController::class, 'show'])->name('pembelian.detail');
Route::get('/exportpembelian', [PembelianController::class, 'pembelianexport'])->name('exportpembelian');

Route::get('/penjualan/data', [PenjualanController::class, 'data'])->name('penjualan.data');
Route::get('/penjualan', [PenjualanController::class, 'index'])->name('penjualan.index');
Route::get('/penjualan/{id}', [PenjualanController::class, 'show'])->name('penjualan.show');
Route::delete('/penjualan/{id}', [PenjualanController::class, 'destroy'])->name('penjualan.destroy');
Route::get('/transaksi/baru', [PenjualanController::class, 'create'])->name('transaksi.baru');
Route::post('/transaksi/simpan', [PenjualanController::class, 'store'])->name('transaksi.simpan');
Route::get('/transaksi/selesai', [PenjualanController::class, 'selesai'])->name('transaksi.selesai');
Route::get('/transaksi/nota-kecil', [PenjualanController::class, 'notaKecil'])->name('transaksi.nota_kecil');

Route::get('/exportpenjualan', [PenjualanController::class, 'penjualanexport'])->name('exportpenjualan');

Route::get('/transaksi/{id}/data', [PenjualanDetailController::class, 'data'])->name('transaksi.data');
Route::get('/transaksi/loadform/{diskon}/{total}/{diterima}', [PenjualanDetailController::class, 'loadForm'])->name('transaksi.load_form');
Route::resource('/transaksi', PenjualanDetailController::class);

Route::get('/laporan', [LaporanController::class, 'index'])->name('laporan.index');
Route::get('/laporan/data/{awal}/{akhir}', [LaporanController::class, 'data'])->name('laporan.data');

Route::get('/setting', [SettingController::class, 'index'])->name('setting.index');
Route::get('/setting/first', [SettingController::class, 'show'])->name('setting.show');
Route::post('/setting', [SettingController::class, 'update'])->name('setting.update');

//ERP Kelompok 2
Route::get('/sso/login',[SSOController::class,'getLogin'])->name('sso.login');
Route::get('/callback',[SSOController::class,'getCallback'])->name('sso.callback');
Route::get('/sso/connect',[SSOController::class,'connectUser'])->name('sso.connect');

app/Models/Pelanggan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pelanggan extends Model
{
    use HasFactory;
    protected $table = 'pelanggan';
    protected $primaryKey = 'id_member';
    protected $guarded = [];

    public function scopeFilter($query)
    {
        if(request('search')){
            return $query->where('kode_member', 'like', '%'. request('search').'%')
                         ->orWhere('nama', 'like', '%'. request('search').'%')
                         ->orWhere('telepon', 'like', '%'. request('search').'%')
                         ->orWhere('alamat', 'like', '%'. request('search').'%');
        }
    }
}

app/Http/Controllers/PelangganController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pelanggan;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use App\Exports\PelangganExport;
use Maatwebsite\Excel\Facades\Excel;
use App\Http\Controllers\Controller;

class PelangganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:pelanggan-list|pelanggan-create|pelanggan-edit|pelanggan-delete', ['only' => ['index','store']]);
         $this->middleware('permission:pelanggan-create', ['only' => ['create','store']]);
         $this->middleware('permission:pelanggan-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:pelanggan-delete', ['only' => ['destroy']]);
    }

    public function pelangganexport()
    {
        return Excel::download(new PelangganExport, 'pelanggan.xlsx');
    }

    public function index()
    {
        return view ('pelanggan.index',[
        "pelanggan"=> Pelanggan::oldest()->filter()->paginate(5)->withQueryString()
        ]);
    }
    public function create()
    {
        return view('pelanggan.create');
    }
    
    public function store(Request $request)
    {
        $request->validate([
            'kode_member' => 'required | unique:pelanggan',
            'nama' => 'required',
            'telepon' => 'required',
            'alamat' => 'required',
        ]);

        $data = new Pelanggan();
        $data->kode_member = $request->kode_member;
        $data->nama = $request->nama;
        $data->telepon = $request->telepon;
        $data->alamat = $request->alamat;
        
        $data->save();

        return redirect()->route('pelanggan.index')->with('success', 'Customer added successful!');
    }

    public function show($id)
    {
        $pelanggan = Pelanggan::find($id);
        return view('pelanggan.show')->with('pelanggan', $pelanggan);
    }

    public function edit($id)
    {
        $pelanggan = Pelanggan::find($id);
        return view('pelanggan.edit')->with('pelanggan', $pelanggan);
    }

    public function update(Request $request, $id)
    {
        $pelanggan = Pelanggan::find($id);
        $input = $request->all();
        $pelanggan->update($input);
        return redirect() ->route('pelanggan.index')
                          ->with('success', 'Customer info updated!');
    }

    public function destroy($id)
    {
        Pelanggan::destroy($id);
        return redirect('pelanggan')->with('success', 'Customer Deleted!');
    }
}

resources/views/pelanggan/create.blade.php
@extends('dashboard.sidebar')
@section('konten')

<div class="container">
           
  <div class="row">
      
      <div class="col-sm-12">
          <div class="home-tab">
            <div class="d-sm-flex align-items-center justify-content-between border-bottom">
              <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                  <a class="nav-link" id="home-tab" data-bs-toggle="tab" href="{{ route('pelanggan.index') }}" role="tab" aria-controls="overview" aria-selected="false">List Member</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active ps-0" id="profile-tab" data-bs-toggle="tab" href="{{ route('pelanggan.create') }}" role="tab" aria-selected="true">Add Member</a>
                </li>
              </ul>
              <div>
                <div class="btn-wrapper">
                  <a class="btn btn-primary"><i class="fas fa-fw fa-user"></i></a>
                </div>
              </div>
            </div>

                  <div class="container-fluid">
                      <div class="col-sm-12">
                          <br>
                          <h2><b class="row justify-content-center">Tambah Member</b></h2>
                          </br>
                      </div>
                  </div>

                  <!-- Konten -->
                  <div class="row justify-content-center">
                    <div class="col-md-8">
                      <div class="card">
                        <div class="card-body">

                        <form action="{{ route('pelanggan.store') }}" method="post">
                          {!! csrf_field() !!}
                          <label>Kode ID</label></br>
                          <input type="text" name="kode_member" id="kode_member" class="form-control"></br>
                          <label>Nama</label></br>
                          <input type="text" name="nama" id="nama" class="form-control"></br>
                          <label>No Telp</label></br>
                          <input type="text" name="telepon" id="telepon" class="form-control"></br>
                          <label>Alamat</label></br>
                          <input type="text" name="alamat" id="alamat" class="form-control"></br>
                          <input type="submit" value="Save" class="btn btn-primary">
                          <span style="float: center">
                          <a class="btn btn-secondary" href="{{ route('pelanggan.index') }}"> Cancel</a>
                        </form>
                    
                        </div>
                      </div>
                    </div>
                  </div>
                  </br>
                  <!-- End -->
          </div>
      </div>
  </div>
</div>
 
@stop

resources/views/pelanggan/edit.blade.php
@extends('dashboard.sidebar')
@section('konten')

<div class="container">
           
  <div class="row">
      
      <div class="col-sm-12">
          <div class="home-tab">
            <div class="d-sm-flex align-items-center justify-content-between border-bottom">
              <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                  <a class="nav-link" id="home-tab" data-bs-toggle="tab" href="{{ route('pelanggan.index') }}" role="tab" aria-controls="overview" aria-selected="false">List Member</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="{{ route('pelanggan.create') }}" role="tab" aria-selected="true">Add Member</a>
                </li>
              </ul>
              <div>
                <div class="btn-wrapper">
                  <a class="btn btn-primary"><i class="fas fa-fw fa-user"></i></a>
                </div>
              </div>
            </div>

                  <div class="container-fluid">
                      <div class="col-sm-12">
                          <br>
                          <h2><b class="row justify-content-center">Edit Member</b></h2>
                          </br>
                      </div>
                  </div>

                      <!-- Konten -->
                      <div class="row justify-content-center">
                        <div class="col-md-8">
                          <div class="card">
                            <div class="card-body">
                            
                            <form action="{{ url('pelanggan/' .$pelanggan->id_member) }}" method="post">
                              {!! csrf_field() !!}
                              @method("PATCH")
                              <input type="hidden" name="id_member" id="id_member" value="{{$pelanggan->id_member}}" id="id" />
                              <label>Kode ID</label></br>
                              <input type="text" name="kode_member" disabled="disabled" id="kode_member" value="{{$pelanggan->kode_member}}" class="form-control"></br>
                              <label>Nama</label></br>
                              <input type="text" name="nama" id="nama" value="{{$pelanggan->nama}}" class="form-control"></br>
                              <label>No Telp</label></br>
                              <input type="text" name="telepon" id="telepon" value="{{$pelanggan->telepon}}" class="form-control"></br>
                              <label>Alamat</label></br>
                              <input type="text" name="alamat" id="alamat" value="{{$pelanggan->alamat}}" class="form-control"></br>
                              <input type="submit" value="Update" class="btn btn-primary">
                              <span style="float: center">
                              <a class="btn btn-secondary" href="{{ route('pelanggan.index') }}"> Cancel</a>
                            </form>
                        
                            </div>
                          </div>
                        </div>
                      </div>
                      </br>
                      <!-- End -->
          </div>
      </div>
  </div>
</div>
 
@stop

resources/views/pelanggan/index.blade.php
@extends('dashboard.sidebar')
@section('konten')
    <div class="container">
           
        <div class="row">
            
            <div class="col-sm-12">
                <div class="home-tab">
                  <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                    <ul class="nav nav-tabs" role="tablist">
                      <li class="nav-item">
                        <a class="nav-link active ps-0" id="home-tab" data-bs-toggle="tab" href="{{ route('pelanggan.index') }}" role="tab" aria-controls="overview" aria-selected="true">List Member</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="{{ route('pelanggan.create') }}" role="tab" aria-selected="false">Add Member</a>
                      </li>
                    </ul>
                    <div>
                      <div class="btn-wrapper">
                        <a class="btn btn-primary"><i class="fas fa-fw fa-user"></i></a>
                      </div>
                    </div>
                  </div>

                <div class="container-fluid">
                    <div class="col-sm-12">
                        <br>
                        <h2><b class="row justify-content-center">Daftar Member</b></h2>
                    </div>
                </div>
                    
                    <!-- Tabel CRUD -->
                    <div class="card-body">
                        
                       <section class="content">
                        <div class="container-fluid">
                            <!-- Small boxes (Stat box) -->
                            <div class="row">
                                <section class="col-md-12">
                                    <div class="card">
                                        <div class="card-body">
                                            <div style="float: right">
                                            <a href="{{ route('exportpelanggan') }}" class="btn btn-success"><i class="fa fa-table"></i> Export</a>
                                            </div>
                                            <form action="/pelanggan">
                                                <div class="col-md-6">
                                                    <div class="input-group mb-3">
                                                        <input type="text" class="form-control" placeholder="Search" name="search" value="{{request('search')}}">
                                                        <button class="btn btn-dark" type="submit" ><i class="fas fa-search fa-sm"></i></button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>

                                        @if ($message = Session::get('success'))
                                            <div class="alert alert-success">
                                                <p>{{ $message }}</p>
                                            </div>
                                        @endif
                                            <table id="example1" class="table table-bordered table-striped">
                                                <thead>
                                                <tr>
                                                    <th>No</th>
                                                    <th>Kode ID</th>
                                                    <th>Nama</th>
                                                    <th>No Telp</th>
                                                    <th>Alamat</th>
                                                    <th>Aksi</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                @foreach($pelanggan as $item)
                                                    <tr>
                                                        <td>{{ $loop->iteration }}</td>
                                                        <td>{{ $item->kode_member }}</td>
                                                        <td>{{ $item->nama }}</td>
                                                        <td>{{ $item->telepon  }}</td>
                                                        <td>{{ $item->alamat }}</td>
                                                        <td>
                                                            
                                                            <a href="{{route('pelanggan.show', $item->id_member)}}" title="show" class="btn btn-sm btn-info"><i class="fa fa-eye"></i></a>
                                                            @can('pelanggan-edit')
                                                            <a href="{{route('pelanggan.edit', $item->id_member)}}" title="edit" class="btn btn-sm btn-warning"><i class="fa fa-edit"></i></a>
                                                            @endcan
                                                            <form method="POST" action="{{route('pelanggan.destroy', $item->id_member)}}" accept-charset="UTF-8" style="display:inline">
                                                                {{ method_field('DELETE') }}
                                                                {{ csrf_field() }}
                                                                @can('pelanggan-delete')
                                                                <button type="submit" class="btn btn-danger btn-sm" title="Delete" onclick="return confirm(&quot;Do you confirm to delete?&quot;)"><i id="delete" class="fa fa-trash"></i></button>
                                                                @endcan
                                                            </form>
                                                           
                                                        </td>
                                                    </tr>
                                                </tbody>
                                                @endforeach
                                            </table>

                                            {{ $pelanggan->links() }}

                                    </div>
                                </section>
                            </div>
                        </div>
                      </section>

                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/pelanggan/show.blade.php
@extends('dashboard.sidebar')
@section('konten')

<div class="container">
           
    <div class="row">
        
        <div class="col-sm-12">
            <div class="home-tab">
              <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                <ul class="nav nav-tabs" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link" id="home-tab" data-bs-toggle="tab" href="{{ route('pelanggan.index') }}" role="tab" aria-controls="overview" aria-selected="false">List Member</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="{{ route('pelanggan.create') }}" role="tab" aria-selected="true">Add Member</a>
                  </li>
                </ul>
                <div>
                  <div class="btn-wrapper">
                    <a class="btn btn-primary"><i class="fas fa-fw fa-user"></i></a>
                  </div>
                </div>
              </div>
  
                    <div class="container-fluid">
                        <div class="col-sm-12">
                            <br>
                            <h2><b class="row justify-content-center">Member</b></h2>
                            </br>
                        </div>
                    </div>

                    <!-- Konten -->
                    <div class="row justify-content-center">
                        <div class="col-md-8">
                            <div class="card">

                                <div class="card-body">
                                    <h5 class="badge badge-success">Kode ID : {{ $pelanggan->kode_member }}</h5>
                                    <p class="card-text">Nama : {{ $pelanggan->nama }}</p>
                                    <p class="card-text">No Telp : {{ $pelanggan->telepon }}</p>
                                    <p class="card-text">Alamat : {{ $pelanggan->alamat }}</p>
                                    <span style="float: right">
                                    <a class="btn btn-primary" href="{{ route('pelanggan.index') }}"> Back</a>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                    </br>
                    <!-- End -->
            </div>
        </div>
    </div>
</div>

@endsection