routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SSO\SSOController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CetegoryController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PelangganController;
use App\Http\Controllers\PembelianController;
use App\Http\Controllers\PenjualanController;
use App\Http\Controllers\PenjualanDetailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [DashboardController::class, 'index']);

Route::resource('/pelanggan', PelangganController::class);
Route::get('/pelanggan', [PelangganController::class, 'index'])->name('pelanggan.index');
Route::get('/create-pelanggan', [PelangganController::class, 'create'])->name('pelanggan.create');
Route::get('edit{id}-pelanggan/', [PelangganController::class, 'edit'])->name('pelanggan.edit');
Route::get('show{id}-pelanggan/', [PelangganController::class, 'show'])->name('pelanggan.show');
Route::get('/exportpelanggan', [PelangganController::class, 'pelangganexport'])->name('exportpelanggan');

Route::resource('/produk', ProdukController::class);
Route::get('/produk', [ProdukController::class, 'index'])->name('produk.index');
Route::get('/create-produk', [ProdukController::class, 'create'])->name('produk.create');
Route::get('edit{id}-produk/', [ProdukController::class, 'edit'])->name('produk.edit');
Route::get('show{id}-pelanggan/', [ProdukController::class, 'show'])->name('produk.detail');
Route::get('/exportproduk', [ProdukController::class, 'produkexport'])->name('exportproduk');

Route::resource('/supplier', SupplierController::class);
Route::get('/supplier', [SupplierController::class, 'index'])->name('supplier.index');
Route::get('create-supplier', [SupplierController::class, 'create'])->name('supplier.create');
Route::get('edit{id}-supplier/', [SupplierController::class, 'edit'])->name('supplier.edit');
Route::get('show{id}-supplier/', [SupplierController::class, 'show'])->name('supplier.show');
Route::get('/exportsupplier', [SupplierController::class, 'supplierexport'])->name('exportsupplier');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
});

Route::resource('kategori', CetegoryController::class);
// Route::get('/exportkategori', [CetegoryController::class, 'kategoriexport'])->name('kategori');


Route::controller(GoogleController::class)->group(function(){
    Route::get('login/google', 'redirectToGoogle')->name('auth.google');
    Route::get('login/google/callback', 'handleGoogleCallback');
});

Route::resource('/pembelian', PembelianController::class);
Route::get('/pembelian', [PembelianController::class, 'index'])->name('pembelian.index');
Route::get('/create-pembelian', [PembelianController::class, 'create'])->name('pembelian.create');
Route::get('show{id}-pembelian/', [PembelianController::class, 'show'])->name('pembelian.detail');
Route::get('/exportpembelian', [PembelianController::class, 'pembelianexport'])->name('exportpembelian');

Route::get('/penjualan/data', [PenjualanController::class, 'data'])->name('penjualan.data');
Route::get('/penjualan', [PenjualanController::class, 'index'])->name('penjualan.index');
Route::get('/penjualan/{id}', [PenjualanController::class, 'show'])->name('penjualan.show');
Route::delete('/penjualan/{id}', [PenjualanController::class, 'destroy'])->name('penjualan.destroy');
Route::get('/transaksi/baru', [PenjualanController::class, 'create'])->name('transaksi.baru');
Route::post('/transaksi/simpan', [PenjualanController::class, 'store'])->name('transaksi.simpan');
Route::get('/transaksi/selesai', [PenjualanController::class, 'selesai'])->name('transaksi.selesai');
Route::get('/transaksi/nota-kecil', [PenjualanController::class, 'notaKecil'])->name('transaksi.nota_kecil');

Route::get('/exportpenjualan', [PenjualanController::class, 'penjualanexport'])->name('exportpenjualan');

Route::get('/transaksi/{id}/data', [PenjualanDetailController::class, 'data'])->name('transaksi.data');
Route::get('/transaksi/loadform/{diskon}/{total}/{diterima}', [PenjualanDetailController::class, 'loadForm'])->name('transaksi.load_form');
Route::resource('/transaksi', PenjualanDetailController::class);

Route::get('/laporan', [LaporanController::class, 'index'])->name('laporan.index');
Route::get('/laporan/data/{awal}/{akhir}', [LaporanController::class, 'data'])->name('laporan.data');

Route::get('/setting', [SettingController::class, 'index'])->name('setting.index');
Route::get('/setting/first', [SettingController::class, 'show'])->name('setting.show');
Route::post('/setting', [SettingController::class, 'update'])->name('setting.update');

//ERP Kelompok 2
Route::get('/sso/login',[SSOController::class,'getLogin'])->name('sso.login');
Route::get('/callback',[SSOController::class,'getCallback'])->name('sso.callback');
Route::get('/sso/connect',[SSOController::class,'connectUser'])->name('sso.connect');

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    use HasFactory;
    protected $table = 'supplier';
    protected $primaryKey = 'id';
    protected $fillable = ['supplier_id', 'supplier_name', 'supplier_address', 'supplier_phone'];

    public function scopeFilter($query)
    {
        if(request('search')){
            return $query->where('supplier_id', 'like', '%'. request('search').'%')
                         ->orWhere('supplier_name', 'like', '%'. request('search').'%')
                         ->orWhere('supplier_address', 'like', '%'. request('search').'%')
                         ->orWhere('supplier_phone', 'like', '%'. request('search').'%');
        }
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Models\Supplier;
use App\Exports\SupplierExport;
use Maatwebsite\Excel\Facades\Excel;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:suplier-list|suplier-create|suplier-edit|suplier-delete', ['only' => ['index','store']]);
         $this->middleware('permission:suplier-create', ['only' => ['create','store']]);
         $this->middleware('permission:suplier-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:suplier-delete', ['only' => ['destroy']]);
    }
    public function supplierexport()
    {
        return Excel::download(new SupplierExport, 'supplier.xlsx');
    }

    public function index()
    {
        return view ('supplier.index',[
        "supplier"=> Supplier::oldest()->filter()->paginate(5)->withQueryString()
        ]);
    }
    public function create()
    {
        return view('supplier.create');
    }
    
    public function store(Request $request)
    {
            $request->validate([
                'supplier_id' => 'required | unique:supplier',
                'supplier_name' => 'required',
                'supplier_address' => 'required',
                'supplier_phone' => 'required',
            ]);
    
            $data = new Supplier();
            $data->supplier_id = $request->supplier_id;
            $data->supplier_name = $request->supplier_name;
            $data->supplier_address = $request->supplier_address;
            $data->supplier_phone = $request->supplier_phone;
            
            $data->save();
    
            return redirect()->route('supplier.index')->with('success', 'Customer added successful!');
    }

    public function show($id)
    {
        $supplier = Supplier::find($id);
        return view('supplier.show')->with('supplier', $supplier);
    }

    public function edit($id)
    {
        $supplier = Supplier::find($id);
        return view('supplier.edit')->with('supplier', $supplier);
    }

    public function update(Request $request, $id)
    {
        $supplier = Supplier::find($id);
        $input = $request->all();
        $supplier->update($input);
        return redirect('supplier')->with('flash_message', 'Supplier info updated!');
    }

    public function destroy($id)
    {
        Supplier::destroy($id);
        return redirect('supplier')->with('flash_message', 'Supplier Deleted!');
    }
}

resources/views/supplier/create.blade.php
@extends('dashboard.sidebar')
@section('konten')

<div class="row">
      
  <div class="col-sm-12">
      <div class="home-tab">
        <div class="d-sm-flex align-items-center justify-content-between border-bottom">
          <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
              <a class="nav-link" id="home-tab" data-bs-toggle="tab" href="{{ route('supplier.index') }}" role="tab" aria-controls="overview" aria-selected="false">List Supplier</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active ps-0" id="profile-tab" data-bs-toggle="tab" href="{{ route('supplier.create') }}" role="tab" aria-selected="true">Add Supplier</a>
            </li>
          </ul>
          <div>
            <div class="btn-wrapper">
              <a class="btn btn-primary"><i class="fas fa-fw fa-user"></i></a>
            </div>
          </div>
        </div>

              <div class="container-fluid">
                  <div class="col-sm-12">
                      <br>
                      <h2><b class="row justify-content-center">Tambah Supplier</b></h2>
                      </br>
                  </div>
              </div>

              <!-- Konten -->
              <div class="row justify-content-center">
                <div class="col-md-8">
                  <div class="card">
                    <div class="card-body">
<div class="card">

  <div class="box-header"class="row justify-content-center"
  <h3><b class="row justify-content-center"></b></h3>
  <div class="card-body">
      
      <form action="{{ url('/supplier') }}" method="post">
        {!! csrf_field() !!}
        <label>ID</label></br>
        <input type="text" name="supplier_id" id="supplier_id" class="form-control"></br>
        <label>Nama</label></br>
        <input type="text" name="supplier_name" id="supplier_name" class="form-control"></br>
        <label>Alamat</label></br>
        <input type="text" name="supplier_address" id="supplier_address" class="form-control"></br>
        <label>No Telepon</label></br>
        <input type="text" name="supplier_phone" id="supplier_phone" class="form-control"></br>
        <input type="submit" value="Save" class="btn btn-success"></br>
    </form>
   
  </div>
</div>
 
@stop

resources/views/supplier/edit.blade.php
@extends('dashboard.sidebar')
@section('konten')

<div class="card">
  <b class="card-header">Edit Supplier</b>
  <div class="card-body">
      
      <form action="{{ url('supplier/' .$supplier->id) }}" method="post">
        {!! csrf_field() !!}
        @method("PATCH")
        <input type="hidden" name="id" id="id" value="{{$supplier->id}}" id="id" />
        <label>ID</label></br>
        <input type="text" name="supplier_id" disabled="disabled" id="supplier_id" value="{{$supplier->supplier_id}}" class="form-control"></br>
        <label>Nama</label></br>
        <input type="text" name="supplier_name" id="supplier_name" value="{{$supplier->supplier_name}}" class="form-control"></br>
        <label>Alamat</label></br>
        <input type="text" name="supplier_address" id="supplier_address" value="{{$supplier->supplier_address}}" class="form-control"></br>
        <label>No Telepon</label></br>
        <input type="text" name="supplier_phone" id="supplier_phone" value="{{$supplier->supplier_phone}}" class="form-control"></br>
        <input type="submit" value="Update" class="btn btn-success"></br>
    </form>
   
  </div>
</div>
 
@stop

resources/views/supplier/index.blade.php
@extends('dashboard.sidebar')
@section('konten')
    <div class="container">
           
        <div class="row">
            
            <div class="col-sm-12">
                <div class="home-tab">
                  <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                    <ul class="nav nav-tabs" role="tablist">
                      <li class="nav-item">
                        <a class="nav-link active ps-0" id="home-tab" data-bs-toggle="tab" href="{{ route('supplier.index') }}" role="tab" aria-controls="overview" aria-selected="true">List Supplier</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="{{ route('supplier.create') }}" role="tab" aria-selected="false">Add Supplier</a>
                      </li>
                    </ul>
                    <div>
                      <div class="btn-wrapper">
                        <a class="btn btn-primary"><i class="fas fa-fw fa-user"></i></a>
                      </div>
                    </div>
                  </div>
                  

                <div class="container-fluid">
                        </div>
                       <br/>
                       <section class="content">
                        <div class="box-body pad">
                            
                            <!-- Small boxes (Stat box) -->
                            <div class="row">
                                <section class="col-md-12">
                                    <div class="card">
                                        <div class="box-header">
                                            <h3>
                                                <div class="col-sm-12">
                                                    <br>
                                                    <h3><b class="row justify-content-center">Data Table Supplier</b></h3>
                                                    </br>
                                                </div>
                                                <div style = "float: left">
                                                    <a href="{{ route('exportsupplier') }}" class="btn btn-outline-success"><i class="fa fa-table"></i> Export Excel</a>
                                                </div>

                                                <div class="row justify-content">
                                                    <div class="col-md-5">
                                                        <form action="/supplier">
                                                            <div class="input-group mb-1">
                                                                <input type="text" class="form-control " placeholder="Search" name="search" value="{{request('search')}}">
                                                                <button class="btn btn-secondary" type="submit" ><i class="fas fa-search fa-sm"></i></button>
                                                            </div>
                                                  
                                            </div>
                                            </h3>
                                        </div>
                                        <div class="card-body">
                                            <table id="example1" class="table table-sm">
                                                <thead>
                                                    <tr>
                                                        <th>No</th>
                                                        <th>ID</th>
                                                        <th>Nama</th>
                                                        <th>Alamat</th>
                                                        <th>No Telepon</th>
                                                        <th>Aksi</th>
                                                    </tr>
    
                                                </thead>
                                                <tbody>
                                                @foreach($supplier as $key => $supplier)
                                                    <tr>
                                                        <td>{{ $key+1 }}</td>
                                                        <td>{{ $supplier->supplier_id }}</td>
                                                        <td>{{ $supplier->supplier_name }}</td>
                                                        <td>{{ $supplier->supplier_address }}</td>
                                                        <td>{{ $supplier->supplier_phone  }}</td>
                                                        <td>

                                                            <a href="{{route('supplier.show', $supplier->id)}}" title="show" class="btn btn-primary btn-sm"><i></i>Detail</a>
                                                            @can('suplier-edit')
                                                            <a href="{{route('supplier.edit', $supplier->id)}}" title="edit" class="btn btn-sm btn btn-secondary"><i class="fa fa-edit"></i></a>
                                                            @endcan
                                                            <form method="POST" action="{{route('supplier.destroy', $supplier->id)}}" accept-charset="UTF-8" style="display:inline">
                                                                {{ method_field('DELETE') }}
                                                                {{ csrf_field() }}
                                                                @can('suplier-delete')
                                                                <button type="submit" class="btn btn-danger btn-sm" title="Delete" onclick="return confirm(&quot;Confirm delete?&quot;)"><i id="delete" class="fa fa-trash"></i></button>
                                                                @endcan
                                                            </form>
                                                        </td>
                                                    </tr>
                                                @endforeach
                                                </tbody>
                                            </table>
            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/supplier/show.blade.php
@extends('dashboard.sidebar')
@section('konten')

<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-8">
          <div class="card">
              <b class="card-header text-center">{{ __('Supplier') }}</b>
              
              <div class="card-body">
                  <h5 class="card-title">ID : {{ $supplier->supplier_id }}</h5>
                  <p class="card-text">Nama : {{ $supplier->supplier_name }}</p>
                  <p class="card-text">Alamat : {{ $supplier->supplier_address }}</p>
                  <p class="card-text">No Telepon : {{ $supplier->supplier_phone }}</p>
              </div>
              
          </div>
      </div>
  </div>
</div>

@endsection