routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\SSO\SSOController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CetegoryController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PelangganController;
use App\Http\Controllers\PembelianController;
use App\Http\Controllers\PenjualanController;
use App\Http\Controllers\PenjualanDetailController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [DashboardController::class, 'index']);

Route::resource('/pelanggan', PelangganController::class);
Route::get('/pelanggan', [PelangganController::class, 'index'])->name('pelanggan.index');
Route::get('/create-pelanggan', [PelangganController::class, 'create'])->name('pelanggan.create');
Route::get('edit{id}-pelanggan/', [PelangganController::class, 'edit'])->name('pelanggan.edit');
Route::get('show{id}-pelanggan/', [PelangganController::class, 'show'])->name('pelanggan.show');
Route::get('/exportpelanggan', [PelangganController::class, 'pelangganexport'])->name('exportpelanggan');

Route::resource('/produk', ProdukController::class);
Route::get('/produk', [ProdukController::class, 'index'])->name('produk.index');
Route::get('/create-produk', [ProdukController::class, 'create'])->name('produk.create');
Route::get('edit{id}-produk/', [ProdukController::class, 'edit'])->name('produk.edit');
Route::get('show{id}-pelanggan/', [ProdukController::class, 'show'])->name('produk.detail');
Route::get('/exportproduk', [ProdukController::class, 'produkexport'])->name('exportproduk');

Route::resource('/supplier', SupplierController::class);
Route::get('/supplier', [SupplierController::class, 'index'])->name('supplier.index');
Route::get('create-supplier', [SupplierController::class, 'create'])->name('supplier.create');
Route::get('edit{id}-supplier/', [SupplierController::class, 'edit'])->name('supplier.edit');
Route::get('show{id}-supplier/', [SupplierController::class, 'show'])->name('supplier.show');
Route::get('/exportsupplier', [SupplierController::class, 'supplierexport'])->name('exportsupplier');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
});

Route::resource('kategori', CetegoryController::class);
// Route::get('/exportkategori', [CetegoryController::class, 'kategoriexport'])->name('kategori');


Route::controller(GoogleController::class)->group(function(){
    Route::get('login/google', 'redirectToGoogle')->name('auth.google');
    Route::get('login/google/callback', 'handleGoogleCallback');
});

Route::resource('/pembelian', PembelianController::class);
Route::get('/pembelian', [PembelianController::class, 'index'])->name('pembelian.index');
Route::get('/create-pembelian', [PembelianController::class, 'create'])->name('pembelian.create');
Route::get('show{id}-pembelian/', [PembelianController::class, 'show'])->name('pembelian.detail');
Route::get('/exportpembelian', [PembelianController::class, 'pembelianexport'])->name('exportpembelian');

Route::get('/penjualan/data', [PenjualanController::class, 'data'])->name('penjualan.data');
Route::get('/penjualan', [PenjualanController::class, 'index'])->name('penjualan.index');
Route::get('/penjualan/{id}', [PenjualanController::class, 'show'])->name('penjualan.show');
Route::delete('/penjualan/{id}', [PenjualanController::class, 'destroy'])->name('penjualan.destroy');
Route::get('/transaksi/baru', [PenjualanController::class, 'create'])->name('transaksi.baru');
Route::post('/transaksi/simpan', [PenjualanController::class, 'store'])->name('transaksi.simpan');
Route::get('/transaksi/selesai', [PenjualanController::class, 'selesai'])->name('transaksi.selesai');
Route::get('/transaksi/nota-kecil', [PenjualanController::class, 'notaKecil'])->name('transaksi.nota_kecil');

Route::get('/exportpenjualan', [PenjualanController::class, 'penjualanexport'])->name('exportpenjualan');

Route::get('/transaksi/{id}/data', [PenjualanDetailController::class, 'data'])->name('transaksi.data');
Route::get('/transaksi/loadform/{diskon}/{total}/{diterima}', [PenjualanDetailController::class, 'loadForm'])->name('transaksi.load_form');
Route::resource('/transaksi', PenjualanDetailController::class);

Route::get('/laporan', [LaporanController::class, 'index'])->name('laporan.index');
Route::get('/laporan/data/{awal}/{akhir}', [LaporanController::class, 'data'])->name('laporan.data');

Route::get('/setting', [SettingController::class, 'index'])->name('setting.index');
Route::get('/setting/first', [SettingController::class, 'show'])->name('setting.show');
Route::post('/setting', [SettingController::class, 'update'])->name('setting.update');

//ERP Kelompok 2
Route::get('/sso/login',[SSOController::class,'getLogin'])->name('sso.login');
Route::get('/callback',[SSOController::class,'getCallback'])->name('sso.callback');
Route::get('/sso/connect',[SSOController::class,'connectUser'])->name('sso.connect');

app/Models/Kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    use HasFactory;

    protected $table = 'kategori';
    protected $primaryKey = 'id_kategori';
    protected $guarded = [];

    public function produk()
    {
        return $this->hasMany(Produk::class);
    }
    public function scopeFilter($query)
    {
        if(request('search')){
            return $query->where('id_kategori', 'like', '%'. request('search').'%')
                         ->orWhere('nama_kategori', 'like', '%'. request('search').'%');
        }
    }
}

resources/views/kategori/create.blade.php
@extends('dashboard.sidebar')
@section('konten')

<div class="container">
           
  <div class="row">
      
      <div class="col-sm-12">
          <div class="home-tab">
            <div class="d-sm-flex align-items-center justify-content-between border-bottom">
              <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                  <a class="nav-link" id="home-tab" data-bs-toggle="tab" href="{{ route('kategori.index') }}" role="tab" aria-controls="overview" aria-selected="false">List Kategori</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active ps-0" id="profile-tab" data-bs-toggle="tab" href="{{ route('kategori.create') }}" role="tab" aria-selected="true">Add Kategori</a>
                </li>
              </ul>
              <div>
                <div class="btn-wrapper">
                  <a class="btn btn-primary"><i class="fas fa-fw fa-user"></i></a>
                </div>
              </div>
            </div>

                  <div class="container-fluid">
                      <div class="col-sm-12">
                          <br>
                          <h2><b class="row justify-content-center">Tambah Kategori</b></h2>
                          </br>
                      </div>
                  </div>

                  <!-- Konten -->
                  <div class="row justify-content-center">
                    <div class="col-md-8">
                      <div class="card">
                        <div class="card-body">

                        <form action="{{ route('kategori.store') }}" method="post">
                          {!! csrf_field() !!}
                          <label>Id Kategori</label></br>
                          <input type="text" name="id_kategori" id="id_kategori" class="form-control"></br>
                          <label>Kategori</label></br>
                          <input type="text" name="nama_kategori" id="nama_kategori" class="form-control"></br>
                          <input type="submit" value="Save" class="btn btn-primary">
                          <span style="float: center">
                          <a class="btn btn-secondary" href="{{ route('kategori.index') }}"> Cancel</a>
                        </form>
                    
                        </div>
                      </div>
                    </div>
                  </div>
                  </br>
                  <!-- End -->
          </div>
      </div>
  </div>
</div>
 
@stop

resources/views/kategori/edit.blade.php
@extends('dashboard.sidebar')
@section('konten')

<div class="container">
           
  <div class="row">
      
      <div class="col-sm-12">
          <div class="home-tab">
            <div class="d-sm-flex align-items-center justify-content-between border-bottom">
              <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                  <a class="nav-link" id="home-tab" data-bs-toggle="tab" href="{{ route('kategori.index') }}" role="tab" aria-controls="overview" aria-selected="false">List Kategori</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="{{ route('kategori.create') }}" role="tab" aria-selected="true">Add Kategori</a>
                </li>
              </ul>
              <div>
                <div class="btn-wrapper">
                  <a class="btn btn-primary"><i class="fas fa-fw fa-user"></i></a>
                </div>
              </div>
            </div>

                  <div class="container-fluid">
                      <div class="col-sm-12">
                          <br>
                          <h2><b class="row justify-content-center">Edit Kategori</b></h2>
                          </br>
                      </div>
                  </div>

                      <!-- Konten -->
                      <div class="row justify-content-center">
                        <div class="col-md-8">
                          <div class="card">
                            <div class="card-body">
                            
                            <form action="{{ url('kategori/' .$kategori->id_kategori) }}" method="post">
                              {!! csrf_field() !!}
                              @method("PATCH")
                              <input type="hidden" name="id_kategori" id="id_kategori" value="{{$kategori->id_kategori}}" id="id" />
                              <label>Id Kategori</label></br>
                              <input type="text" name="kode_kategori" disabled="disabled" id="kode_kategori" value="{{$kategori->kode_kategori}}" class="form-control"></br>
                              <label>Nama</label></br>
                              <input type="text" name="nama_kategori" id="nama_kategori" value="{{$kategori->nama_kategori}}" class="form-control"></br>
                             <input type="submit" value="Update" class="btn btn-primary">
                              <span style="float: center">
                              <a class="btn btn-secondary" href="{{ route('kategori.index') }}"> Cancel</a>
                            </form>
                        
                            </div>
                          </div>
                        </div>
                      </div>
                      </br>
                      <!-- End -->
          </div>
      </div>
  </div>
</div>
 
@stop

resources/views/kategori/index.blade.php
@extends('dashboard.sidebar')
@section('konten')
    <div class="container">
           
        <div class="row">
            
            <div class="col-sm-12">
                <div class="home-tab">
                  <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                    <ul class="nav nav-tabs" role="tablist">
                      <li class="nav-item">
                        <a class="nav-link active ps-0" id="home-tab" data-bs-toggle="tab" href="{{ route('kategori.index') }}" role="tab" aria-controls="overview" aria-selected="true">List Kategori</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="{{ route('kategori.create') }}" role="tab" aria-selected="false">Add Kategori</a>
                      </li>
                    </ul>
                    <div>
                      <div class="btn-wrapper">
                        <a class="btn btn-primary"><i class="fas fa-fw fa-user"></i></a>
                      </div>
                    </div>
                  </div>

                <div class="container-fluid">
                    <div class="col-sm-12">
                        <br>
                        <h2><b class="row justify-content-center">Daftar Kategori</b></h2>
                    </div>
                </div>
                    
                    <!-- Tabel CRUD -->
                    <div class="card-body">
                        
                       <section class="content">
                        <div class="container-fluid">
                            <!-- Small boxes (Stat box) -->
                            <div class="row">
                                <section class="col-md-12">
                                    <div class="card">
                                        <div class="card-body">
                                            <div style="float: right">
                                            <a href="#" class="btn btn-success"><i class="fa fa-table"></i> Export</a>
                                            </div>
                                            <form action="/kategori">
                                                <div class="col-md-6">
                                                    <div class="input-group mb-3">
                                                        <input type="text" class="form-control" placeholder="Search" name="search" value="{{request('search')}}">
                                                        <button class="btn btn-dark" type="submit" ><i class="fas fa-search fa-sm"></i></button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>

                                        @if ($message = Session::get('success'))
                                            <div class="alert alert-success">
                                                <p>{{ $message }}</p>
                                            </div>
                                        @endif
                                            <table id="example1" class="table table-bordered table-striped">
                                                <thead>
                                                <tr>
                                                    <th>No</th>
                                                    <th>Kategori</th>
                                                    <th>Aksi</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                @foreach($kategori as $item)
                                                    <tr>
                                                        <td>{{ $loop->iteration }}</td>
                                                        <td>{{ $item->nama_kategori }}</td>
                                                        <td>
                                                            
                                                            <a href="{{route('kategori.show', $item->id_kategori)}}" title="show" class="btn btn-sm btn-info"><i class="fa fa-eye"></i></a>
                                                            @can('kategori-edit')
                                                            <a href="{{route('kategori.edit', $item->id_kategori)}}" title="edit" class="btn btn-sm btn-warning"><i class="fa fa-edit"></i></a>
                                                            @endcan
                                                            <form method="POST" action="{{route('kategori.destroy', $item->id_kategori)}}" accept-charset="UTF-8" style="display:inline">
                                                                {{ method_field('DELETE') }}
                                                                {{ csrf_field() }}
                                                                @can('kategori-delete')
                                                                <button type="submit" class="btn btn-danger btn-sm" title="Delete" onclick="return confirm(&quot;Do you confirm to delete?&quot;)"><i id="delete" class="fa fa-trash"></i></button>
                                                                @endcan
                                                            </form>
                                                           
                                                        </td>
                                                    </tr>
                                                </tbody>
                                                @endforeach
                                            </table>

                                            {{ $kategori->links() }}

                                    </div>
                                </section>
                            </div>
                        </div>
                      </section>

                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/kategori/show.blade.php
@extends('dashboard.sidebar')
@section('konten')

<div class="container">
           
    <div class="row">
        
        <div class="col-sm-12">
            <div class="home-tab">
              <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                <ul class="nav nav-tabs" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link" id="home-tab" data-bs-toggle="tab" href="{{ route('kategori.index') }}" role="tab" aria-controls="overview" aria-selected="false">List Member</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="{{ route('kategori.create') }}" role="tab" aria-selected="true">Add Member</a>
                  </li>
                </ul>
                <div>
                  <div class="btn-wrapper">
                    <a class="btn btn-primary"><i class="fas fa-fw fa-user"></i></a>
                  </div>
                </div>
              </div>
  
                    <div class="container-fluid">
                        <div class="col-sm-12">
                            <br>
                            <h2><b class="row justify-content-center">Kategori</b></h2>
                            </br>
                        </div>
                    </div>

                    <!-- Konten -->
                    <div class="row justify-content-center">
                        <div class="col-md-8">
                            <div class="card">

                                <div class="card-body">
                                    <h5 class="badge badge-success">Kode ID : {{ $kategori->id_kategori }}</h5>
                                    <p class="card-text">Kategori : {{ $kategori->nama_kategori }}</p>
                                    <span style="float: right">
                                    <a class="btn btn-primary" href="{{ route('kategori.index') }}"> Back</a>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                    </br>
                    <!-- End -->
            </div>
        </div>
    </div>
</div>

@endsection